/**
 * Broker-owned trusted evidence (the trust-boundary fix). This type is NEVER
 * deserialized from an adapter registration frame, never produced by an adapter
 * manifest, and never mutable by adapter code. It is generated by broker-owned
 * validation code (the conformance runner running under broker control, a
 * real-runtime validation, or a policy sign-off) and resolved at registration time
 * from a broker-local registry keyed by adapter identity.
 *
 * Authentication identifies the connection; it does NOT make an adapter's security
 * claims true. So the values that AWARD a tier (provenance + verified flags) live
 * here, on the broker side, and the adapter frame may carry only DECLARATIONS.
 *
 * In-memory only for this PR — no persistence, no schema change.
 */

import { ComponentRole } from '../identity/components.js';

/** Where the broker's evidence came from. Set by broker validation code, never an adapter. */
export type TrustedEvidenceSource =
  | 'none'
  | 'conformance_runner'        // deterministic conformance pass (fake runtime) ⇒ conformance_tested
  | 'real_runtime_validation'   // proven against an actual host ⇒ real_runtime_validated
  | 'policy_signed_off';        // real-runtime + human/policy sign-off ⇒ supported

export const TRUSTED_EVIDENCE_SOURCES: readonly TrustedEvidenceSource[] = [
  'none', 'conformance_runner', 'real_runtime_validation', 'policy_signed_off',
];

/** The conformance-contract version this build understands. */
export const SUPPORTED_CONFORMANCE_VERSION = 1 as const;

/** Broker-owned, identity-bound evidence. Adapter code can neither construct nor mutate it. */
export interface BrokerTrustedEvidence {
  source: TrustedEvidenceSource;
  /** Identity binding — evidence for (adapterId, adapterVersion, role) only. */
  adapterId: string;
  adapterVersion: string;
  role: ComponentRole;
  /** Optional validated package/build identity, when available. */
  buildId?: string;
  capabilities: {
    sendVerified: boolean;
    manualReceiveVerified: boolean;
    checkpointReceiveVerified: boolean;
    liveReceiveVerified: boolean;
    ackReplyVerified: boolean;
  };
  durability: { brokerRestartVerified: boolean; reconnectVerified: boolean; queuedDeliveryVerified: boolean };
  security: { fencingVerified: boolean; redactionVerified: boolean; packagedRuntimeVerified: boolean };
  conformanceVersion?: number;
  evidenceId?: string;
}

/** What an adapter is asked to bind its evidence to — used to reject A's evidence for B. */
export interface EvidenceQuery {
  adapterId: string;
  adapterVersion: string;
  role: ComponentRole;
  buildId?: string;
}

export type EvidenceRejectReason =
  | 'absent'
  | 'adapter_id_mismatch'
  | 'adapter_version_mismatch'
  | 'role_mismatch'
  | 'build_mismatch'
  | 'unsupported_conformance_version'
  | 'unknown_source';

export interface EvidenceResolution {
  ok: boolean;
  evidence?: BrokerTrustedEvidence;
  reason?: EvidenceRejectReason;
}

/**
 * A broker-local, in-memory registry of trusted evidence. Only broker-owned code
 * (the conformance runner, a real-runtime validator, a policy step) calls `record`.
 * `resolve` is the ONLY way the registration path obtains evidence, and it enforces
 * identity binding + version support. Absent ⇒ fails closed.
 */
export class TrustedEvidenceRegistry {
  private byKey = new Map<string, BrokerTrustedEvidence>();

  private key(adapterId: string, adapterVersion: string, role: ComponentRole): string {
    return `${adapterId} :: ${adapterVersion} :: ${role}`;
  }

  /** Broker-owned validation code records evidence. NOT reachable from an adapter frame. */
  record(ev: BrokerTrustedEvidence): void {
    if (ev.source === 'none') return; // 'none' is the absence sentinel; never stored
    this.byKey.set(this.key(ev.adapterId, ev.adapterVersion, ev.role), ev);
  }

  /** Resolve evidence for an exact identity. Fails closed on any mismatch / absence. */
  resolve(q: EvidenceQuery): EvidenceResolution {
    const ev = this.byKey.get(this.key(q.adapterId, q.adapterVersion, q.role));
    if (!ev) return { ok: false, reason: 'absent' };
    if (ev.adapterId !== q.adapterId) return { ok: false, reason: 'adapter_id_mismatch' };
    if (ev.adapterVersion !== q.adapterVersion) return { ok: false, reason: 'adapter_version_mismatch' };
    if (ev.role !== q.role) return { ok: false, reason: 'role_mismatch' };
    // buildId is part of the EXACT identity tuple: presence/absence is symmetric. A
    // query without a buildId must NOT match evidence pinned to a specific build, and a
    // query with a buildId must NOT match build-agnostic evidence — otherwise an adapter
    // could omit (or invent) buildId to escape/borrow build-scoped evidence. Compare with
    // a null-normalized equality so undefined and a value never cross-match.
    if ((q.buildId ?? null) !== (ev.buildId ?? null)) return { ok: false, reason: 'build_mismatch' };
    if (!(TRUSTED_EVIDENCE_SOURCES as readonly string[]).includes(ev.source)) return { ok: false, reason: 'unknown_source' };
    if (ev.conformanceVersion !== undefined && ev.conformanceVersion !== SUPPORTED_CONFORMANCE_VERSION) return { ok: false, reason: 'unsupported_conformance_version' };
    return { ok: true, evidence: ev };
  }

  /** Test/maintenance: forget all evidence. */
  clear(): void { this.byKey.clear(); }
}
