/**
 * Guard against the beta.3 release-blocker: the product version is duplicated across
 * package.json, src/protocol/version.ts (XBUS_VERSION), and .claude-plugin/plugin.json.
 * If they DISAGREE, a clean `xbus install` fails contract validation
 * (metadata-version-disagree) and rolls back — exactly the first-run failure beta.3
 * fixes. This test makes any future divergence a CI failure, not a release surprise.
 */
import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { XBUS_VERSION, PROTOCOL_VERSION } from '../../src/protocol/version.js';
import { assertVersionConsistency } from '../../src/tools/write-provenance.js';
import { SCHEMA_VERSION, WIRE_COMPATIBILITY_ID } from '../../src/protocol/handshake.js';
import { exactBuildId, resolveIdentity, SECURE_TRANSPORT_VERSION } from '../../src/shared/build-identity.js';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const readJson = (p: string) => JSON.parse(fs.readFileSync(path.join(REPO, p), 'utf8')) as Record<string, unknown>;

// The AUTHORITATIVE release identity for this line. Bumping the product prerelease
// (beta.N) is a deliberate, reviewed act: change this literal and every surface
// below must move with it. Compatibility + schema are INDEPENDENT of the product
// version and must NOT move just because the prerelease label did.
const EXPECTED_PRODUCT_VERSION = '0.1.0-beta.4';
const EXPECTED_COMPATIBILITY_ID = 'xbus-p1-stp1-s6';
const EXPECTED_SCHEMA_VERSION = 6;

describe('version consistency (prevents the beta.3 install-rollback class)', () => {
  it('the authoritative product version is exactly the expected release identity', () => {
    // Pin the literal so a forgotten bump (the beta.3→beta.4 release-blocker where the
    // functional merge shipped but the product metadata stayed beta.3) is a CI failure,
    // not a self-contradicting published artifact.
    expect(XBUS_VERSION, 'XBUS_VERSION is the single source of truth').toBe(EXPECTED_PRODUCT_VERSION);
  });

  it('package.json, XBUS_VERSION, and .claude-plugin/plugin.json all agree', () => {
    const pkg = readJson('package.json').version;
    const plugin = readJson('.claude-plugin/plugin.json').version;
    expect(pkg, 'package.json vs XBUS_VERSION').toBe(XBUS_VERSION);
    expect(plugin, 'plugin.json vs XBUS_VERSION').toBe(XBUS_VERSION);
  });

  it('package-lock.json version fields track the product version', () => {
    // Both the top-level and the root-package ("") lockfile version fields are
    // release surfaces; a stale lockfile version misreports the packaged identity.
    const lock = readJson('package-lock.json') as { version?: string; packages?: Record<string, { version?: string }> };
    expect(lock.version, 'package-lock.json top-level version').toBe(XBUS_VERSION);
    expect(lock.packages?.['']?.version, 'package-lock.json root-package version').toBe(XBUS_VERSION);
  });

  it('compatibility + schema are INDEPENDENT of the product version and stay at s6', () => {
    // A product prerelease bump must never silently move the wire compatibility tuple
    // or the schema integer. These stay fixed unless protocol/STP/schema genuinely change.
    expect(WIRE_COMPATIBILITY_ID, 'wire compatibility tuple').toBe(EXPECTED_COMPATIBILITY_ID);
    expect(SCHEMA_VERSION, 'schema version').toBe(EXPECTED_SCHEMA_VERSION);
    expect(PROTOCOL_VERSION, 'application protocol').toBe(1);
    expect(SECURE_TRANSPORT_VERSION, 'XBUS-STP wire version').toBe(1);
  });

  it('the resolved runtime identity (what CLI `version` + `doctor` report) carries the product version', () => {
    // `xbus version` / `doctor this_build` derive product version + exact build id from
    // resolveIdentity(). Assert the source-run identity (no provenance) reports the
    // expected product version and a build id that embeds it — the value a clean install
    // (via generated provenance) will likewise embed.
    const id = resolveIdentity(SCHEMA_VERSION, null);
    expect(id.productVersion, 'resolveIdentity productVersion').toBe(EXPECTED_PRODUCT_VERSION);
    expect(id.compatibilityId, 'resolveIdentity compatibilityId').toBe(EXPECTED_COMPATIBILITY_ID);
    expect(id.schemaVersion).toBe(EXPECTED_SCHEMA_VERSION);
    expect(id.buildId, 'exact build id embeds the product version').toBe(exactBuildId(EXPECTED_PRODUCT_VERSION, 'source'));
    expect(id.buildId.startsWith(`xbus-${EXPECTED_PRODUCT_VERSION}-`)).toBe(true);
  });

  it('a generated provenance manifest (if built) embeds the product version + s6 tuple', () => {
    // provenance.json is generated by the build (postbuild write-provenance) and read
    // at install time as the EXACT identity. When present in the built repo, it must
    // agree with the authoritative version; skip cleanly on an unbuilt checkout.
    const provPath = path.join(REPO, 'provenance.json');
    if (!fs.existsSync(provPath)) return; // unbuilt source checkout — nothing to assert
    const prov = JSON.parse(fs.readFileSync(provPath, 'utf8')) as Record<string, unknown>;
    expect(prov.productVersion, 'provenance productVersion').toBe(EXPECTED_PRODUCT_VERSION);
    expect(prov.compatibilityId, 'provenance compatibilityId').toBe(EXPECTED_COMPATIBILITY_ID);
    expect(prov.schemaVersion, 'provenance schemaVersion').toBe(EXPECTED_SCHEMA_VERSION);
    expect(String(prov.buildId).startsWith(`xbus-${EXPECTED_PRODUCT_VERSION}-`), 'provenance buildId embeds product version').toBe(true);
  });

  it('the build-time gate passes on the real (consistent) tree', () => {
    expect(() => assertVersionConsistency(REPO)).not.toThrow();
  });

  it('the build-time gate FAILS (would fail the build) on a forced mismatch', () => {
    // Build an isolated copy with a tampered plugin.json version; the gate must throw.
    const os = require('node:os') as typeof import('node:os');
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'xbus-vc-'));
    fs.mkdirSync(path.join(tmp, '.claude-plugin'), { recursive: true });
    fs.writeFileSync(path.join(tmp, 'package.json'), JSON.stringify({ version: XBUS_VERSION }));
    fs.writeFileSync(path.join(tmp, '.claude-plugin', 'plugin.json'), JSON.stringify({ version: '0.0.0-bad' }));
    try {
      expect(() => assertVersionConsistency(tmp)).toThrow(/version disagreement|disagree/i);
    } finally {
      fs.rmSync(tmp, { recursive: true, force: true });
    }
  });

  it('the engines range excludes the not-yet-validated Node 25+', () => {
    const engines = (readJson('package.json').engines as { node?: string } | undefined)?.node ?? '';
    expect(engines).toMatch(/<\s*25/); // upper bound below 25
    expect(engines).toMatch(/>=\s*22/); // lower bound at 22
  });
});
